services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "7007:7007"
    environment:
      NODE_ENV: development
      BACKEND_SECRET: your-backend-secret # Replace this in production
      GITHUB_TOKEN: ${GITHUB_TOKEN} # Replace with your GitHub token
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: backstage
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
    volumes:
      - ./app-config.yaml:/app/app-config.yaml:ro
      - ./app-config.local.yaml:/app/app-config.local.yaml:ro
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    volumes:
      - backstage-db:/var/lib/postgresql/data

volumes:
  backstage-db: